# Generated by Django 6.1 on 2026-09-09 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('highschool', 'Highschool'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('doctoral', 'Doctoral')], default='full-time', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
