# Generated by Django 6.1 on 2026-09-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
