# Generated by Django 6.1 on 2026-09-20 22:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_education_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('language', 'Language'), ('soft-skill', 'Soft-Skill'), ('hard-skill', 'Hard-Skill')], max_length=20)),
                ('language_level', models.CharField(choices=[('native', 'Native'), ('first-language', 'First Language'), ('fluent', 'Fluent'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], max_length=30, null=True)),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('highschool', 'Highschool'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('doctoral', 'Doctoral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('bootcamp', 'Bootcamp')], max_length=20),
        ),
    ]
