# Generated by Django 6.1 on 2026-09-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skill_alter_education_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='language_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert / Native')], default='expert', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('highschool', 'Highschool'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('doctoral', 'Doctoral')], default='bachelors', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('bootcamp', 'Bootcamp')], default='full-time', max_length=20),
        ),
    ]
